on:
  push:
    paths:
      - README.md.in
      - .github/workflows/readme.yml
  pull_request:
    paths:
      - README.md.in
      - .github/workflows/readme.yml
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1.3.2
        with:
          neovim: true
        id: neovim
      - name: Render README.md
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.13/pandoc-3.1.13-1-amd64.deb
          sudo apt install -y ./pandoc-3.1.13-1-amd64.deb
          git clone https://github.com/jonathanfilip/vim-lucius vim-lucius
          wget https://github.com/lyokha/vim-publish-helper/archive/refs/tags/0.15.tar.gz \
              -Ovim-publish-helper.tar.gz
          tar xvf vim-publish-helper.tar.gz
          wget https://github.com/lyokha/vim-publish-helper/releases/download/0.15/vimhl-0.15-${{ runner.os }}-ghc-9.8 \
              -Ovimhl
          chmod a+x vimhl
          sed -i "1s'.*'&\nset runtimepath+=$(pwd)/vim-lucius\nset runtimepath+=$(pwd)/vim-publish-helper-0.15'" \
              .vimrc.pandoc
          export VIMHL_BACKEND=${{ steps.neovim.outputs.executable }}
          export VIMRC_PANDOC="$(pwd)/.vimrc.pandoc"
          pandoc -fmarkdown -tgfm -Fvimhl README.md.in > README.md
          git config --local user.name "github-actions[bot]"
          git config --local user.email \
              "github-actions[bot]@users.noreply.github.com"
          git commit README.md -m "Render README.md"
          git remote set-url origin \
              "https://lyokha:${{ secrets.GITHUB_COMMIT_README }}@github.com"`
             `"/${{ github.repository }}"
          git push origin $BRANCH_NAME

